--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/ezratweaver/wallpaper/nordwall2.jpg"

-- Special
background="#282c34"
foreground="#f0f2f4"
cursor="#f0f2f4"

-- Colors
color0="#98c379"
color1="#e5C07b"
color2="#e06c75"
color3="#98c379"
color4="#61afef"
color5="#56b6c2"
color6="#c678dd"
color7="#98c379"
color8="#e5c07b"
color9="#e5c07b"
color10="#e06c75"
color11="#61afef"
color12="#abb2bf"
color13="#61afef"
color14="#abb2bf"
color15="#e06c75"
