# Shell variables
# Generated by 'wal'
wallpaper='/home/ezratweaver/wallpaper/nordwall2.jpg'

# Special
background='#282c34'
foreground='#f0f2f4'
cursor='#f0f2f4'

# Colors
color0='#98c379'
color1='#e5C07b'
color2='#e06c75'
color3='#98c379'
color4='#61afef'
color5='#56b6c2'
color6='#c678dd'
color7='#98c379'
color8='#e5c07b'
color9='#e5c07b'
color10='#e06c75'
color11='#61afef'
color12='#abb2bf'
color13='#61afef'
color14='#abb2bf'
color15='#e06c75'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
