--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/ezratweaver/wallpaper/muscle-car-ice-road-red-moon.jpg"

-- Special
background="#050406"
foreground="#c0c0c0"
cursor="#c0c0c0"

-- Colors
color0="#050406"
color1="#A22933"
color2="#CF2C36"
color3="#EA333A"
color4="#A23F4F"
color5="#F65D48"
color6="#FB984F"
color7="#c0c0c0"
color8="#434244"
color9="#A22933"
color10="#CF2C36"
color11="#EA333A"
color12="#A23F4F"
color13="#F65D48"
color14="#FB984F"
color15="#c0c0c0"
